### ISSUE TITLE
Relative path not working.

### ISSUE THREAD

**Issue by peterehik-px** [stellar-expert/soroban-build-workflow#1]
Whenever I try to run the workflow with a contract defined in a separate directory, I get this error during the docker run step

```
/usr/local/bin/entrypoint.sh: line 17: cd: [hello_world]: No such file or directory
rustc 1.82.0 (f6e511eec 2024-10-15)
cargo 1.82.0 (8f40fc59f 2024-08-21)
stellar 22.0.0 (7abcaeb65cf254602a7e0fe6c552d3813bcb5bfe)
stellar-xdr 22.0.0-rc.1.1 (72e523004b5906eb1829990f9b14d2f0fa3018f0)
xdr curr (529d[51](https://github.com/peterehik/soroban-playground/actions/runs/12147475959/job/33873793332#step:5:52)76f24c73eeccfa5eba481d4e89c19b1181)
ERROR: Cargo.toml file does not exist
```

Here's my sample workflow

```
name: Build and Release 
on:
  push: 
    tags:
      - 'v*'  # triggered whenever a new tag (prefixed with "v") is pushed to the repository

permissions:  # required permissions for the workflow
  id-token: write
  contents: write
  attestations: write

jobs:
  release-contract-ybs:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@8764eba5769e4ffb63883889c2db5cc12eb44ef8 #v22.0.0
    with:
      release_name: ${{ github.ref_name }}          # use git tag as unique release name
      release_description: 'Hello world contract release'       
      relative_path: '["hello_world"]'  
      package: 'soroban-hello-world-contract'
    secrets:  # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}
```   

I definitely have a folder called hello_world in the root of my repository and that's where the contract is defined.
